# -*- coding: utf-8 -*-
"""Relational Database Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1C8ARbb8EzQMe105vG4_ayuWnboXthmyy

Member 1: 

Member 2:

Design and implement a >1 table relational database project with Python and SQLite.

Your project should perform the standard CRUD operations plus at least 1 aggregation function.

Task: (self proposed eg manage a contact list)

ER-diagram:

Table specification:
- students(sid&, sname)

& primary key
^ foreign key

Python implementation:
"""

# program menu

import sqlite3

# create database connection
connection = sqlite3.connect("school.db")

# create cursor
cursor = connection.cursor()

# execute SQL query
#cursor.execute("DELETE FROM ccas WHERE cid = 7")
cursor.execute("SELECT * FROM ccas;")

results = cursor.fetchall()

for record in results:
    print(record[1])

# make changes permanent
connection.commit()

# destroy database connection (and cursor)
connection.close()

"""Sample SQL queries:
```
# create table 
cursor.execute("CREATE TABLE IF NOT EXISTS contacts (rid INTEGER, name TEXT, dob TEXT, email TEXT, mobile TEXT);")
 
# insert
cursor.execute("INSERT INTO contacts (rid, name, dob, email, mobile) VALUES (1, 'Lim Ah Seng', '1995-01-01', 'limahseng@hotmail.com', '12345678');")


# select
cursor.execute("SELECT * FROM contacts;")

# update
cursor.execute("UPDATE contacts SET mobile = '88888888' WHERE rid = 1;")

# delete
cursor.execute("DELETE FROM contacts WHERE rid = 2;")
```
"""